[tool.ruff]
line-length = 200
fix = true
[tool.ruff.format]
#quote-style = "single"
indent-style = "space"
# 启用 docstring 代码片段格式化
docstring-code-format = true
skip-magic-trailing-comma = false

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B", "SIM", "I", "PL"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501", "SIM102", "SIM108", "SIM113", "SIM300", "PLC1901", "PLR0904", "PLR0911", "PLR0912", "PLR0913", "PLR0914", "PLR0915", "PLR0916", "PLR0917", "PLR1702", "PLR2004", "PLR6301", "PLW0602", "PLW0603", "PLW2901",]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

extend-select = ["W", "E"]
preview = true


# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]
