[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["E501", "SIM102", "SIM108", "SIM113", "SIM300", "PLC1901", "PLR0904", "PLR0911", "PLR0912", "PLR0913", "PLR0914", "PLR0915", "PLR0916", "PLR0917", "PLR1702", "PLR2004", "PLR6301", "PLW0602", "PLW0603", "PLW2901", "PLR1714"]
unfixable = ["B"]
extend-select = ["W", "E"]
preview = true
